version: '3'

tasks:
  default:
    desc: task list
    cmds:
      - npx task --list
    silent: true

includes:
  cspell:
    dir: ./cspell
    taskfile: ./cspell/Taskfile.yml
  cli:
    dir: ./packages/go-task-cli
    taskfile: ./packages/go-task-cli/Taskfile.yml
  setup:
    dir: ./packages/setup-go-task-cli
    taskfile: ./packages/setup-go-task-cli/Taskfile.yml

