version: '3'

tasks:
  build:
    desc: build
    deps:
      - clean
    cmds:
      - npm exec -- tsup ./src/cli.ts --out-dir ./build --config ./tsconfig.json --no-external --external @ryusuke410/setup-go-task-cli
  clean:
    desc: clean
    cmds:
      - rm -rf ./build
  build-and-pack:
    desc: build and pack
    vars:
      releasesDir: './releases'
    deps:
      - build
    cmds:
      - mkdir -p {{.releasesDir}}
      - npm pack --pack-destination {{.releasesDir}}
  update-go-task-cli:
    desc: update go-task-cli
    cmds:
      - rm -rf ./go-task-cli
      - task: go-task-cli:build-and-pack
      - task: unpack
      - cp go-task-cli/package.json src/go-task-cli-package.json
      - npm exec -- tsx ./scripts/remove-gtc-from-go-task-cli-package.ts ./src/go-task-cli-package.json
      - cp override/* ./go-task-cli
  link:
    desc: link this package
    vars:
      releasesDir: './releases'
      packageJsonText:
        sh: cat '{{.TASKFILE_DIR}}/package.json'
      packageVersion: '{{(mustFromJson .packageJsonText).version}}'
      packageTarGz: '{{.TASKFILE_DIR}}/{{.releasesDir}}/ryusuke410-setup-go-task-cli-{{.packageVersion}}.tgz'
    dir: '{{.releasesDir}}'
    cmds:
      - rm -rf package
      - tar -xf {{.packageTarGz}}
      - task: link-internal
  unlink:
    desc: unlink this package
    vars:
      releasesDir: './releases'
    preconditions:
      - sh: "[ -d '{{.releasesDir}}/package' ]"
    cmds:
      - task: unlink-internal
  publish-dry-run:
      - task: build-and-pack
      - echo "content of package:"
      - task: publish-dry-run-internal
  publish:
    desc: publish
    cmds:
      - task: build
      - npm publish --access public

  unpack:
    internal: true
    silent: true
    cmds:
      - npm exec -- tsx ./scripts/unpack.ts
  link-internal:
    internal: true
    silent: true
    vars:
      releasesDir: './releases'
    dir: '{{.releasesDir}}/package'
    cmds:
      - npm unlink @ryusuke410/setup-go-task-cli
      - npm link @ryusuke410/setup-go-task-cli
  unlink-internal:
    internal: true
    silent: true
    vars:
      releasesDir: './releases'
    dir: '{{.releasesDir}}/package'
    cmds:
      - npm unlink @ryusuke410/setup-go-task-cli
  publish-dry-run-internal:
    internal: false
    silent: true
    vars:
      packageJsonText:
        sh: cat '{{.TASKFILE_DIR}}/package.json'
      packageVersion: '{{(mustFromJson .packageJsonText).version}}'
      packageTarGz: '{{.TASKFILE_DIR}}/{{.releasesDir}}/ryusuke410-setup-go-task-cli-{{.packageVersion}}.tgz'
      fileList:
        sh: echo -n "$(tar -tf "{{.packageTarGz}}")"
    indent: 4
    cmds:
      - echo '{{indent 4 .fileList}}'

includes:
  go-task-cli:
    dir: ../go-task-cli
    taskfile: ../go-task-cli/Taskfile.yml
    internal: true
