version: '3'

tasks:
  build:
    desc: build
    deps:
      - clean
    cmds:
      - npm exec -- tsup ./src/cli.ts --out-dir ./build --config ./tsconfig.json --no-external --external @ryusuke410/setup-go-task-cli
  clean:
    desc: clean
    cmds:
      - rm -rf ./build
  build-and-pack:
    desc: build and pack
    deps:
      - build
    cmds:
      - mkdir -p {{.setupGoTaskCli_releasesDir}}
      - npm pack --pack-destination {{.setupGoTaskCli_releasesDir}}
  update-go-task-cli:
    desc: update go-task-cli
    cmds:
      - rm -rf ./go-task-cli
      - task: go-task-cli:build-and-pack
      - task: unpack
      - cp go-task-cli/package.json src/go-task-cli-package.json
      - cp override/* ./go-task-cli
  link:
    desc: link this package
    dir: '{{.setupGoTaskCli_releasesDir}}'
    cmds:
      - rm -rf package
      - tar -xf {{.setupGoTaskCli_packageTarGz}}
      - task: link-internal
  unlink:
    desc: unlink this package
    preconditions:
      - sh: "[ -d '.{{.setupGoTaskCli_releasesDir}}/package' ]"
    cmds:
      - task: unlink-internal
  publish-dry-run:
      - task: build-and-pack
      - echo "content of package:"
      - task: publish-dry-run-internal
  publish:
    desc: publish
    cmds:
      - task: build
      - npm publish --access public

  unpack:
    internal: true
    silent: true
    cmds:
      - npm exec -- tsx ./scripts/unpack.ts
  link-internal:
    internal: true
    silent: true
    dir: '{{.setupGoTaskCli_releasesDir}}/package'
    cmds:
      - npm unlink
      - npm link
  unlink-internal:
    internal: true
    silent: true
    dir: '{{.setupGoTaskCli_releasesDir}}/package'
    cmds:
      - npm unlink
  publish-dry-run-internal:
    internal: false
    silent: true
    vars:
      fileList:
        sh: echo -n "$(tar -tf "{{.setupGoTaskCli_packageTarGz}}")"
    indent: 4
    cmds:
      - echo '{{indent 4 .fileList}}'

includes:
  go-task-cli:
    dir: ../go-task-cli
    taskfile: ../go-task-cli/Taskfile.yml
    internal: true

# NOTE: vars cannot be defined locally
vars:
  setupGoTaskCli_releasesDir: './releases'
  setupGoTaskCli_packageJsonText:
    sh: cat ./package.json
  setupGoTaskCli_packageVersion: '{{(mustFromJson .setupGoTaskCli_packageJsonText).version}}'
  setupGoTaskCli_packageTarGz: '{{.TASKFILE_DIR}}/{{.setupGoTaskCli_releasesDir}}/ryusuke410-setup-go-task-cli-{{.setupGoTaskCli_packageVersion}}.tgz'
